Replaced old twitter icon with new icon
Virtual-Coffee/virtualcoffee.io pull request #1124
Opened 2024-01-30 17:34 UTC by antriksh-9

## Linked Issue

Closes #1112.

## Description

On the [website](https://virtualcoffee.io/) under navbar section the twitter logo was old one.
I changed it to the new logo.

![Screenshot 2024-01-30 230417](https://github.com/Virtual-Coffee/virtualcoffee.io/assets/132576984/17622eff-18c0-49d6-82bb-162ed70860a6)

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

2024-02-01 18:06 UTC, adiati98 commented on app/components/Nav.tsx
> +								viewBox="0 0 512 512"
Hi @antriksh-9,
Is there any reason to remove the `role="img"` attribute and change the `viewBox` dimension?

2024-02-01 18:09 UTC, adiati98 commented on app/components/Nav.tsx
>  								<title>Twitter</title>
You might also want to change this from "Twitter" to "X".

```suggestion
								<title>X</title>
```

2024-02-02 04:04 UTC, antriksh-9 commented
Hey @adiati98 I have made the necessary changes.

2024-02-02 13:48 UTC, danieltott requested changes
Check my comment - we definitely needed the viewbox change - now the icon isn't showing up!

![image](https://github.com/Virtual-Coffee/virtualcoffee.io/assets/360261/1702534b-754e-46de-b011-3cf138f9be66)

2024-02-02 13:48 UTC, danieltott commented on app/components/Nav.tsx
>  								viewBox="0 0 24 24"
Looks like we needed that viewbox change - not sure what the problem there was...

If you update that we can get this up!

```suggestion
								viewBox="0 0 512 512"
```

2024-02-06 14:19 UTC, danieltott approved these changes
Looks good - thanks @antriksh-9!

2024-02-06 14:19 UTC, merged