Add November 2024 newsletter to the website
Virtual-Coffee/virtualcoffee.io pull request #1291
Opened 2024-11-11 20:24 UTC by adiati98

## Linked Issue

Closes #1290 

## Description

This PR adds November 2024 newsletter to the website and updates the data in the `newsletters.ts` file.

## Methodology

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

2024-11-29 20:26 UTC, adiati98 commented
@BekahHW @danieltott @meg-gutshall, November is almost end.
Can anyone review and merge this November newsletter PR? Thanks! 😄

2024-11-30 16:26 UTC, meg-gutshall requested changes

2024-11-30 16:26 UTC, meg-gutshall commented on src/content/newsletters/2024-11.jsx
> +				count for this challenge.
**typo/grammar:**

```suggestion
				While we love good documentation here at Virtual Coffee, <code>README</code> docs or
				anything else you would typically consider documentation, don't
				count for this challenge.
```

2024-11-30 16:26 UTC, meg-gutshall commented on src/content/newsletters/2024-11.jsx
> +				<Link href="/monthlychallenges">monthly challenge page</Link>, and learn
**suggestion:** Edit for clarity

```suggestion
				<Link href="/monthlychallenges">monthly challenge page</Link>. Learn
```

2024-11-30 16:26 UTC, meg-gutshall commented on src/content/newsletters/2024-11.jsx
> +				<li>
**issue:** Missing new time

```suggestion
				<li>
				  The Pack Hunt (Tandem Job Hunting) (Wednesdays at 10:00 AM ET | Wednesdays at 10:00 PM ET)</li>
				<li>
```

2024-11-30 16:26 UTC, meg-gutshall commented on src/content/newsletters/2024-11.jsx
> +					some the roles
**typo:**

```suggestion
					some of the roles
```

2024-11-30 18:57 UTC, meg-gutshall approved these changes
Thank you, queen!

2024-11-30 18:57 UTC, merged