Create a new July 2022 challenge
Virtual-Coffee/virtualcoffee.io pull request #599
Opened 2022-06-23 22:25 UTC by JayRKyd

## Linked Issue

Closes #594 

## Description

I added a new monthly challenge for July 2022

## Methodology

Every month virtual coffee has a new monthly challenge

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

2022-06-30 12:56 UTC, BekahHW requested changes
Thanks so much for getting this together, @JayRKyd. There's a couple of updates I'd like to see to help with formatting on the page. Let me know if you can get to them this week. No worries if you can't.

2022-06-30 12:56 UTC, BekahHW commented on app/routes/monthlychallenges/july-2022.jsx
> +			<div className="alert alert-success">
This div with the alert-success needs to be removed. We add these when a challenge is completed, so it was probably there from the last challenge.

2022-06-30 12:56 UTC, BekahHW commented on app/routes/monthlychallenges/july-2022.jsx
> +			<h3>How it works</h3>
I know this was in the content, but I think we can remove the <h3> with "How it works".

2022-06-30 12:56 UTC, BekahHW commented on app/routes/monthlychallenges/july-2022.jsx
> +			<li>
Let's wrap the `<li>s` in an `<ul>`.

So it will look like this:

```
<ol>
<li></li>
<li></li>
</ol>
```

2022-06-30 12:56 UTC, BekahHW commented on app/routes/monthlychallenges/july-2022.jsx
> +			<li>Participate in 15 standups;</li>
Let's wrap these `<li>s` in a `<ul>` as well.

2022-06-30 12:56 UTC, BekahHW commented on app/routes/monthlychallenges/july-2022.jsx
> +			<li>
Wrap the `<li>s` in a `<ul>`

2022-06-30 12:56 UTC, BekahHW commented on app/routes/monthlychallenges/july-2022.jsx
> +			<li>Test the exact workflow(s) you are planning to demo</li>
Wrap the `<li>s` in a `<ul>`

2022-06-30 12:56 UTC, BekahHW commented on app/routes/monthlychallenges/july-2022.jsx
> +			<li>
Wrap the `<li>s` in a `<ul>`

2022-07-02 17:46 UTC, blackgirlbytes commented
Hey @JayRKyd! I wish I could sit down and help you, but I can't :( on vacation. However, I did make the necessary updates on this PR. You just have to press merge pull request on this link -- > https://github.com/JayRKyd/virtualcoffee.io/pull/1

2022-07-05 11:21 UTC, BekahHW commented
![men charging on the battlefield with git merge caption](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

2022-07-05 11:22 UTC, merged