Add October 2022 newsletter to website
Virtual-Coffee/virtualcoffee.io pull request #657
Opened 2022-10-04 09:48 UTC by adiati98

## Linked Issue

Closes #644 

## Description

- Add the October 2022 newsletter.
- Update `newsletter.js` to add the issue to the index.

## Methodology

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

2022-10-04 12:56 UTC, danieltott requested changes
Hey @adiati98 -

I know we haven't been doing this a lot previously with the newsletters, but I'd like to try to use `Link` for internal links going forward (for all content).

We'll need to import it at the top of the file:

```js
import { Link } from '@remix-run/react';
```

And then we can replace any `<a href=...` with `<Link to=...` for any links that are on our site (any links starting with `https://virtualcoffee.io/`

Let me know if that doesn't make sense

2022-10-04 12:56 UTC, danieltott commented on app/routes/__frontend/newsletter/issues/2022-10.jsx
> +				<a href="https://virtualcoffee.io/monthlychallenges/sept-2022">
Can we try to use `Link` for internal links?

```suggestion
				<Link to="/monthlychallenges/sept-2022">
```

2022-10-04 13:07 UTC, adiati98 commented
@danieltott let me do the revisions and I'll get back to you whenever I have questions 😊

Do you want the revision only in October's newsletter, or within all newsletters?

2022-10-04 13:17 UTC, danieltott commented
Just this one is fine for now 👍🏼

2022-10-04 18:09 UTC, adiati98 commented
@danieltott I've replaced the `a href` with `link to` and pushed the changes.
Please let me know if I need to revise anything at all 😄

2022-10-04 19:04 UTC, adiati98 commented
@danieltott I'm already away from my computer and just realized that I haven't update this branch with `main` 🤦🏻‍♀️

Sorry! If I need to do that, I'll do it tomorrow morning 😅

Thanks, Dan!

2022-10-04 19:52 UTC, danieltott approved these changes
![approved](https://media.tenor.com/eDScsLHR67IAAAAM/approved-target-lady.gif)

2022-10-04 19:52 UTC, merged

2022-10-05 19:05 UTC, adiati98 commented
@danieltott 
![woop woop GIF](https://media.giphy.com/media/Y4nmq4GOnLf4XIgALX/giphy.gif)