Added new page for Developer Health resources.  Starting with "Burnout"
Virtual-Coffee/virtualcoffee.io pull request #685
Opened 2022-10-10 20:27 UTC by chaos986

## Linked Issue

#673 

## Description

I made a new page and pasted in text from slack and videos from YouTube. 

I am still new to Markdown and React.  

I previewed nothing. 

This could break prod. 

## Methodology

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

2022-10-10 20:58 UTC, JoeKarow requested changes

2022-10-10 20:58 UTC, JoeKarow commented on app/routes/__frontend/resources/developer-health/index.mdx
> +#Burnout
Need a space between '#' & "Burnout"

2022-10-10 21:07 UTC, chaos986 commented on app/routes/__frontend/resources/developer-health/index.mdx
> +#Burnout
done

2022-10-14 17:19 UTC, BekahHW commented
This is looking good, @chaos986. I have a couple of comments about structuring the page.

Let's start by changing Burnout to "Managing burnout". 

I've updated the content to read more like a blog post. I should've put this in the issue, so that's on me. I think the section will work out to be more like a collection of guides.

[Here's the updated version.](https://docs.google.com/document/d/15GyVHEkWPEWNAHitgLwow-C4h-1JW9_6no_9O5T9jXU/edit?usp=sharing)

Below that, add a section heading for "Video Resources".

Let me know if you have questions.

2022-10-26 16:51 UTC, BekahHW commented
@chaos986 wanted to check-in here. How are things going? Do you need support?

2022-11-01 18:41 UTC, merged